openssl/openssl

CHANGES
NEWS
README
include/openssl/opensslv.h

1.1.0f release commits

---

CHANGES
NEWS
README
TABLE
crypto/opensslv.h
openssl.spec

1.0.2l release commits

---

README
include/openssl/opensslv.h

1.1.1-pre6 auto commits

---

README
include/openssl/opensslv.h

1.1.1 pre8 release commits

---

README
include/openssl/opensslv.h

1.1.1-pre9 release commits

---

CHANGES
NEWS
README
include/openssl/opensslv.h

1.1.1a release commits

---

CHANGES
NEWS
README
include/openssl/opensslv.h

1.1.0j release commits

---

CHANGES
NEWS
README
crypto/Makefile
crypto/conf/Makefile
crypto/opensslv.h
crypto/rand/Makefile
openssl.spec
util/libeay.num

1.0.2q release commits

---

CHANGES
NEWS
README
include/openssl/opensslv.h

1.1.1d release commits

---

CHANGES
NEWS
README
crypto/bn/Makefile
crypto/ec/Makefile
crypto/opensslv.h
openssl.spec
util/libeay.num

1.0.2 release commits

---

CHANGES
NEWS
README
crypto/opensslv.h
openssl.spec

Automated commits for the 1.0.2u release

1.0.2u release commits

---

crypto/x509/x_pubkey.c

It uses EVP_PKEY serializers to get the desired results.

Adapt i2d_PUBKEY for provider only keys

---

crypto/perlasm/x86_64-xlate.pl

It turns out that GNU as and Solaris as don't have compatible ideas on
the .section syntax, so we need to check if we're using GNU as or
another assembler and adapt this .section syntax accordingly.
Fixes #11132

crypto/perlasm/x86_64-xlate.pl: detect GNU as to deal with quirks

---

crypto/crmf/crmf_lib.c

The code in this function was almost entirely a copy of the
functionality in ASN1_item_sign(), so it gets refactored to actually
call ASN1_item_sign(), and thereby automatically gets support for
EVP_PKEYs with only provider side keys.

Refactor CRMF_poposigningkey_init() to work with provider keys

---

doc/man3/OSSL_PARAM_allocate_from_text.pod

DOCS: Fix the description of OSSL_PARAM_allocate_from_text()

---

CHANGES
NEWS
README
include/openssl/opensslv.h

Marked as urgent because these are for the release.
For review by @InfoHunter

Release commits for 1.1.1e

---

crypto/ec/ec_backend.c
providers/implementations/keymgmt/ec_kmgmt.c

The provider key export functions for EC_KEY assumed that a public key
is always present, and would fail if not.  This blocks any attempt to
export a key structure with only domain parameters.
This is similar to earlier work done in EVP_PKEY_ASN1_METHODs.

PROV: Fix EC_KEY exporters to allow domain parameter keys

---

CHANGES
NEWS
README
include/openssl/opensslv.h

111f release commits

---

CHANGES
NEWS
README
include/openssl/opensslv.h

1.1.1h release commits

---

crypto/ocsp/ocsp_cl.c
crypto/ocsp/ocsp_srv.c
crypto/x509/x509_cmp.c

This is a minor follow-up on #12615.

Make more use of X509_add_certs(); minor related code & comments cleanup
