- .travis.yml
Apparently trusty image has newer clang, there is no need to pull
clang-3.9 packages. Also pull golang when actually needed.
[extended tests]
> WIP: .travis.yml: minor facelift

- crypto/x509/x_pubkey.c
With the provided method of creating the new X509_PUBKEY, an extra
EVP_PKEY is created and needs to be properly cleaned away.
(note: we could choose to keep it just as well, but there are
consequences, explained in a comment in the code)
> X509_PUBKEY_set(): Fix memory leak

- crypto/x509/x_pubkey.c
- include/openssl/serializer.h
It's already used internally, there's no reason the DER serializer
propqueries shouldn't be present alongside the PEM and TEXT ones.
> Add OSSL_SERIALIZER_PUBKEY_TO_DER_PQ and friends

- crypto/asn1/i2d_pr.c
It uses EVP_PKEY serializers to get the desired results.
One might think that ddoing this might make things a bit dicy for
existing serializers, as they should obviously use i2d functions.
However, since our serializers use much more primitive functions
such as i2d_ASN1_INTEGER(), or keytype specific ones such as
i2d_RSAPrivateKey(), there is no clash.
> Adapt i2d_PrivateKey for provider only keys

- doc/man3/BIO_f_buffer.pod
The BIO_f_buffer() documentation tells in enough detail how it affects
BIO_gets(), but not how it affects BIO_read_ex().  This change
remedies that.
Fixes #10859
-----
This is an alternative to #10876
> DOC: document in more detail what a BIO_read_ex() via BIO_f_buffer() does

- Configurations/unix-Makefile.tmpl
- doc/internal/man3/evp_keymgmt_newdata.pod
- util/find-doc-nits
Because we generate an increasing number of POD files, some of them
end up in the build tree.  This makes it difficult for find-doc-nits
to work as desired when the build tree is separate from the source
tree.
The best supported way to make it work in such an environment is to
run it from the build tree and let it use the build information from
configdata.pm to find all the POD files.  To make this smooth enough,
we add a function 'files' that returns an array of file names
corresponding to criteria from the caller.
> Make util/find-doc-nits runnable from the build tree

- crypto/evp/evp_fetch.c
- crypto/evp/evp_local.h
- crypto/evp/exchange.c
- crypto/evp/keymgmt_lib.c
- crypto/evp/p_lib.c
- doc/internal/man3/evp_keymgmt_util_export_to_provider.pod
- doc/internal/man3/evp_pkey_make_provided.pod
- include/crypto/evp.h
- test/keymgmt_internal_test.c
Previously, evp-keymgmt_util_export_to_provider() took care of all
kinds of exports of EVP_PKEYs to provider side keys, be it from its
legacy key or from another provider side key.  This works most of the
times, but there may be cases where the caller wants to be a bit more
in control of what sort of export happens when.
Also, when it's time to remove all legacy stuff, that job will be much
easier if we have a better separation between legacy support and
support of provided stuff, as far as we can take it.
This changes moves the support of legacy key to provider side key
export from evp-keymgmt_util_export_to_provider() to
evp_pkey_make_provided(), and makes sure the latter is called from all
EVP_PKEY functions that handle legacy stuff.
> Refactor evp_pkey_make_provided() to do legacy to provider export

- CHANGES
- include/openssl/__DECC_INCLUDE_EPILOGUE.H
- include/openssl/__DECC_INCLUDE_PROLOGUE.H
This only affects __DECC_INCLUDE_EPILOGUE.H and __DECC_INCLUDE_PROLOGUE.H,
which are used automatically by HP and VSI C/C++ compilers.
> VMS: mitigate for the C++ compiler that doesn't understand certain pragmas

- Configurations/descrip.mms.tmpl
- Configurations/unix-Makefile.tmpl
- Configurations/windows-makefile.tmpl
- INSTALL.md
- NOTES.VALGRIND
- test/README.ssltest.md
- util/perl/OpenSSL/Test.pm
- util/wrap.pl
util/wrap.pl is a script that defines the environment variables
OPENSSL_ENGINES and OPENSSL_MODULES, then calls the command line
that's given as its arguments.
On a POSIX platform, the command line call is done via
util/shlib_wrap.sh to ensure that the shared library paths are
correct.  For other platforms, util/wrap.pl currently assumes that
similar things are already in place through other means.
-----
This is an alternative to #11100
> TEST: add util/wrap.pl and use it

- crypto/dsa/dsa_lib.c
- crypto/evp/evp_local.h
- crypto/evp/keymgmt_lib.c
- crypto/evp/keymgmt_meth.c
- crypto/evp/p_lib.c
- doc/man7/provider-keymgmt.pod
- include/crypto/dsa.h
- include/crypto/evp.h
- include/openssl/core_numbers.h
- providers/implementations/keymgmt/dh_kmgmt.c
- providers/implementations/keymgmt/dsa_kmgmt.c
- providers/implementations/keymgmt/ec_kmgmt.c
- providers/implementations/keymgmt/rsa_kmgmt.c
This is an adaptation of the following functions for provided keys:
EVP_PKEY_copy_parameters()
EVP_PKEY_missing_parameters()
EVP_PKEY_cmp_parameters()
EVP_PKEY_cmp()
This also adds the necessary EVP_KEYMGMT interfaces to support those functions, and the implementations for RSA, DSA and DH.
This replaces #11025 and is built on top of #11148
> EVP: Adapt EVP_PKEY checking, comparing and copying for provider keys, take 3

- .travis.yml
Where we build out of source, the source directory was _srcdist and
the build directory was _build.  That gives the same nesting level for
both, which doesn't quite exercise all aspects of relative back
references from build to source tree.
Changing the build tree to be in _build/tree will challenge back
references a bit more, and ensure a bit more that we got it right.
> .travis.yml: where it matters, have build and source nesting levels differ

- Configure
- config
The 'config' script checked for a bunch of crypto/ sub-system
directories, and added 'no-' options if they weren't there.
We move it to 'Configure' in an effort to simplify 'config' for
further work.
Note: this is pretty much a historical thing.  In modern OpenSSL, it's
much simpler to edit the SUBDIRS statement in crypto/build.info.
However, it's been claimed the there are those who still remove some
of these sub-system sources.
> config, Configure: move the check of removed crypto/ sub-systems

- doc/man3/X509_LOOKUP.pod
- doc/man3/X509_LOOKUP_meth_new.pod
- doc/man3/X509_STORE_add_cert.pod
- util/private.num
Most of all, the base X509_LOOKUP functionality is now documented.
Furthermore, the names X509_LOOKUP_METHOD and X509_STORE are added for
reference.
Some functions were moved from X509_LOOKUP_meth_new.pod
> DOC: Add documentation related to X509_LOOKUPs [1.1.1]

- providers/implementations/ciphers/cipher_aes_ocb.c
- providers/implementations/ciphers/ciphercommon.c
- providers/implementations/ciphers/ciphercommon_block.c
Avoid function calls we don't need to do.
In 1.1.1 we have:
aes-128-cbc     572267.80k   681197.08k   715430.74k   720508.59k   722359.64k   723004.07k
Current master:
aes-128-cbc     460663.70k   631125.66k   701283.58k   719794.52k   724732.59k   726668.63k
new:
aes-128-cbc     582057.64k   684288.62k   715721.90k   724856.15k   717578.24k   727176.53k
> Improve small block cipher performance

- util/wrap.pl
Acting on EXE_SHELL was a bit over the top, especially in light of
instructions like this (from NOTES.VALGRIND):
EXE_SHELL="`/bin/pwd`/util/wrap.pl valgrind --error-exitcode=1 --leak-check=full -q"
Fixes #11255
> util/wrap.pl: do not look at EXE_SHELL

- doc/man7/provider-keymgmt.pod
Some type specs didn't correspond to actual use.
> DOCS: Fix documentation on asymmetric keydata types

- crypto/dh/dh_ameth.c
- crypto/dh/dh_lib.c
- crypto/dsa/dsa_ameth.c
- crypto/ec/ec_ameth.c
- crypto/evp/m_sigver.c
- crypto/evp/pmeth_fn.c
- crypto/evp/signature.c
- crypto/rsa/rsa_ameth.c
- include/crypto/dh.h
The EVP_PKEY_ASN1_METHOD function export_to() must check that the key
we're trying to export has a known libcrypto method, i.e. is a built
in RSA_METHOD, DSA_METHOD, etc.  Otherwise, the method may be defined
by the calling application, by an engine, by another library, and we
simply cannot know all the quirks hidden behind that method, if we
have access to the key data, or much anything.
Such keys are simply deemed impossible to export to provider keys,
i.e. have export_to() return 0.  This cascades back to functions like
evp_pkey_export_to_provider() and evp_pkey_upgrade_to_provider() and
their callers.  In most cases, this is fine, but if these get mixed in
with provider side keys in any function, that function will fail.
Fixes #11179
Fixes #9915
> EVP: Check that key methods aren't foreign when exporting

- crypto/evp/evp_local.h
- crypto/evp/keymgmt_lib.c
- crypto/evp/keymgmt_meth.c
- crypto/evp/p_lib.c
- crypto/evp/pmeth_gn.c
- crypto/evp/pmeth_lib.c
- crypto/rsa/rsa_lib.c
- doc/man3/EVP_PKEY_gen.pod
- doc/man7/provider-keymgmt.pod
- include/crypto/evp.h
- include/openssl/core_names.h
- include/openssl/core_numbers.h
- include/openssl/evp.h
- include/openssl/rsa.h
- providers/implementations/keymgmt/rsa_kmgmt.c
- test/evp_test.c
- test/recipes/30-test_evp_data/evppkey.txt
- util/libcrypto.num
This turned out to be a fairly big ordeal.  To begin with, our libcrypto<->provider interface couldn't support the way things are done in the EVP_PKEY API in a sane manner, so this needed to be redesigned a bit.
Furthermore, domparam and key generation use an application callback to give the user some feedback when the key is created, and that support needs to be extended to providers.  However, it would be very unsafe to just pass some random function pointer directly to the provider methods, so with some inspiration from `BN_GENCB`, I created a new callback type that is used by libcrypto to pass the necessary data to the provider, which then ends up calling an upcall that knows exactly how to handle that structure.
Please read the individual commits for more information.
NOTE: apart …
> Implement domparam and key generation

- Configurations/15-android.conf
- NOTES.ANDROID
According to forum discussions with NDK developers, ANDROID_NDK_HOME
is used for something else.
Fixes #11205
> Andoid cross compile: change ANDROID_NDK_HOME to ANDROID_NDK_ROOT

- Configurations/15-android.conf
This target gave '-pie' as a C flag when it should be a linker flag.
Additionally, we add '-fPIE' as C flag for binaries.
Fixes #11237
> Configurations: Fix "android" configuration target

- crypto/rsa/rsa_local.h
The first field was called 'pad', but not for the reason one might
think.  It was really a padding int that was always zero, and was
placed first on purpose.  This is to pick up programming errors where
an RSA pointer was passed when an EVP_PKEY pointer should have been,
an makes it look like an EVP_PKEY structure with type EVP_PKEY_NONE,
which effectively avoids any further processing (and unintended
corruption of the RSA structure).
This is only relevant for legacy structure and EVP_PKEY_METHODs.  With
providers, EVP_PKEYs aren't passed to the backend anyway.
> Fix RSA structure

- crypto/evp/pmeth_lib.c
The keytype number will only be -1 when control commands are used for
more than one key type.  Sometimes, they share the same underlying
structure, and sometimes not.
Some of the RSA control commands that are using only with the keytype
EVP_PKEY_RSA we misplaced to be handled with the keytype -1.
> Fix legacy_ctrl_to_param() to pay better attention to keytype

- crypto/dh/dh_ameth.c
- crypto/dsa/dsa_ameth.c
- crypto/ec/ec_ameth.c
- crypto/ec/ecx_meth.c
- crypto/rsa/rsa_ameth.c
The export-to-provider functions for DH, DSA and EC_KEY assumed that a
public key is always present, and would fail if not.  This blocks any
attempt to export a key structure with only domain parameters.
While fixing this, we also modify the selection declaration to
evp_keymgmt_import() to be more adaptive, the diverse selection bits
are now added when the corresponding data is added to the OSSL_PARAM
array.
> DH, DSA, EC_KEY: Fix exporters to allow domain parameter keys

- util/wrap.pl
On Unix, a caught signal that exits the process does so with an exit
code that is 'signal | 128'.  This modifies util/wrap.pl to mimic
that.
> util/wrap.pl: Correct exit code when signalled

- crypto/ec/ec_curve.c
We can find no reason why everyone should have to call both
EC_curve_nist2nid() and ec_curve_name2nid() to find the NID for a
name, and it's too easy to forget EC_curve_nist2nid(), so we make life
simpler.
One could argue that FIPS only allows a limited set of names, but that
now gets handled internally, and those who really want to be really
sure to only get the NIST names can still do so with EC_curve_nist2nid()
> EC: Refactor ec_curve_name2nid() to accept NIST curve names

- Configurations/windows-makefile.tmpl
The Windows command line has its limits, and we're hitting it hard.
We therefore generate one 'del' command for each explicit file for the
'clean' target.
Fixes #11163
> Windows makefile generator: Don't delete long lists of files in one go

- CHANGES.md
Fixed one ambiguous line and removed a few unnecessary backticks.
> Fixups in CHANGES.md

- apps/cmp.c
- crypto/cmp/cmp_client.c
- crypto/cmp/cmp_ctx.c
- crypto/cmp/cmp_local.h
- crypto/cmp/cmp_protect.c
- crypto/cmp/cmp_vfy.c
- doc/man3/OSSL_CMP_CTX_new.pod
- doc/man3/OSSL_CMP_validate_msg.pod
- include/openssl/cmp.h
- test/cmp_ctx_test.c
- test/cmp_vfy_test.c
- util/libcrypto.num
This just does some renaming for API consistency and name brevity.
> OSSL_CMP_CTX: rename field and its getter/setter from 'untrusted_certs' to 'untrusted'

- apps/pkcs12.c
- doc/man1/openssl-pkcs12.pod.in
Make the option order consistent in the help output and in the POD file.
Give warnings when an option is ignored because` -export` is given or missing.
> apps/pkcs12.c: Improve user guidance, re-ordering no-export vs. export options

- doc/man3/SSL_CTX_set_cert_verify_callback.pod
- doc/man3/SSL_want.pod
- include/openssl/ssl.h.in
- ssl/ssl_lib.c
- ssl/statem/statem_clnt.c
- ssl/statem/statem_local.h
- test/helpers/handshake.c
- test/helpers/ssl_test_ctx.c
- test/helpers/ssl_test_ctx.h
- test/recipes/80-test_ssl_new.t
- test/ssl-tests/03-custom_verify.cnf
- test/ssl-tests/03-custom_verify.cnf.in
- test/sslapitest.c
- util/other.syms
During TLS handshake it happens that servers do not provide their full certificate chain or that sufficiently fresh cert status info is not available at the client end.
Before calling `SSL_connect()`, client applications may provide a certificate verification callback function via `SSL_CTX_set_cert_verify_callback()` to help out by fetching and inserting missing certs, CRLs, OCSP responses, or the like. This unfortunately does not work fine if there are other TLS connections that must not be blocked while fetching such data and the client application is not threaded.
A simple way out would be to let the callback function make `SSL_connect()` return to the calling application, which releases the lock on concurrent TLS connections, with a code similar to `SSL_ERROR_WANT_READ`. 
Then the app …
> SSL_connect: Enable non-threaded TLS client apps to fetch missing server certs or status info

- crypto/x509/x509_vfy.c
This PR ...
* ~optimizes `build_chain()` by pruning currently not valid (expired) untrusted certs right away,
such that they are not even tried to be used as candidate issuers during the chain building loop.~
* includes code cleanup motivated by #11359 (where I [stated](https://github.com/openssl/openssl/pull/11359#issuecomment-703067291) that the `goto`s in `internal_verify()` should be eliminated),
* improves the maintainability and the coding style in `x509_vfy.c` (without actual semantics changes)
* ~two fixes on keeping the value of the `self_signed` variable current in `build_chain()`~
* ~allows `NULL` arg to `OPENSSL_sk_dup` and  `OPENSSL_deep_copy`, which then return an empty stack, and~
* ~adds the new internal function `X509_add_certs_new()`, which simplifies handling of …
> Refactor x509_vfy.c for code cleanup

- Configurations/unix-Makefile.tmpl
- providers/build.info
Simplify use of `run_tests`, both in the (Unix) Makefile itself, and for external use.
For instance, when selectively running tests, one often uses, e.g.,
```
make tests TESTS=test_x509
```
Yet this re-builds all prerequisites - which is good for basic use, but when doing quick experiments it can be a hassle having to wait untll even unrelated stuff gets re-compiled.
With the new `run_tests` target, experiences users can selectively re-build what they need and then call a pretty lean
```
make run_tests TESTS=test_x509
```
Moreover, after switching branches and re-building without `make clean`, it can happen easily that tests fail as follows:
```
Error loading config from file ../../test/fips-and-base.cnf
40478974377F0000:error:1C8000D6:Provider routines:SELF_TEST_post:module integrity …
```
> Makefile: improve run_tests

- apps/dgst.c
- apps/dhparam.c
- apps/dsaparam.c
- apps/gendsa.c
- apps/genpkey.c
- apps/genrsa.c
- apps/include/apps.h
- apps/lib/apps.c
- apps/req.c
This has been motivated by #12077.
This PR also introduces `app_keygen()` and `app_paramgen()`,
factoring out the respective low-level calls and the diagnostics around them
in `dgst`, `dhparam`, `dsaparam`, `gendsa`, `genpkey`, `genrsa`, and `req`,
and cleans up error reporting and coding style in a couple of these apps.
> APPS key/param gen: Add warning on delay due to missing entropy; clean up error handling

- providers/implementations/ciphers/cipher_aes_gcm.c
- providers/implementations/ciphers/cipher_aria_ccm.c
- providers/implementations/ciphers/cipher_aria_gcm.c
- providers/implementations/ciphers/cipher_sm4_ccm.c
- providers/implementations/ciphers/cipher_sm4_gcm.c
- test/evp_test.c
Hit two regressions in dupctx tests from my addition of those methods in the various ciphers.  Fix them up
> Issue 22076 - Fix regressions in dupctx testing
